name: Release & Publish

# When a release is published
on:
  release:
    types: [published]

jobs:
  publishWindows:
    env:
      VERSION: ${{ github.event.release.tag_name }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build, Pack, Push
        run: |
          cd crunch.NET
          dotnet restore crunch.NET.csproj
          dotnet build crunch.NET.csproj --configuration Release -p:Version=${{ env.VERSION }}
          dotnet pack crunch.NET.csproj --output nupkgs --configuration Release -p:Version=${{ env.VERSION }}
          dotnet nuget push nupkgs\*.nupkg -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
